all:
  children:
    ubuwebservers:
      hosts:
        web1 : 
        web2 :
      vars:
        ansible_user: ubuntu
    centwebservers:
      hosts:
        cent1:
        cent2:
        cent3:
      vars:
        ansible_user: centos
    ungrouped:
      hosts:
        controller: {}
    webservers:
      children:
        ubuwebservers:
        centwebservers:
