apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    app: web
  name: simple-webapp-color-red
  namespace: production
spec:
  containers:
  - env:
    - name: APP_COLOR
      value: red
    image: thtom/webappcolor
    name: simple-webapp-color-red
    ports:
    - containerPort: 8080
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}