apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: webapp-color-nodeport
  name: webapp-color-nodeport
  namespace: production
spec:
  ports:
  - name: 80-8080
    nodePort: 30008
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web
  type: NodePort