# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
    config.vm.define "minikube" do |minikube|
      minikube.vm.box = "bytesguy/ubuntu-server-21.10-arm64"
      minikube.vm.hostname = "minikube"
      minikube.vm.provider "vmware_desktop" do |v|
        v.vmx["memsize"] = 4096
        v.vmx["numvcpus"] = 2
      end
      minikube.vm.provision :shell do |shell|
        shell.path = "install_minikube.sh"
      end
    end
  end