- name: play1
  hosts: centwebservers
  become: true
  tasks:
    - name: Installation Apache2 & curl
      yum:
        name:
          - curl
          - httpd
        state: latest
        update_cache: yes
    - name: Activation service apache
      systemd:
        name: httpd
        state: started
        enabled: yes
  tags:
    - apache
    - curl

