# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

    config.vm.box = "bytesguy/ubuntu-server-21.10-arm64"
    config.vm.box_version = "1.0.0"
    config.vm.provision "shell", inline: <<-SHELL
       apt-get update
       curl -fsSL https://get.docker.com -o get-docker.sh
       sudo sh get-docker.sh
       sudo usermod -aG docker vagrant
       sudo systemctl enable docker
       sudo systemctl start docker
       echo "L'adresse IP de votre machine $HOSTNAME est : $(ip -f inet addr show enp1s4 | sed -En -e 's/.*inet ([0-9.]+).*/\1/p')"
    SHELL
  end
  