apiVersion: v1
kind: Pod
metadata:
  name: simple-webapp-color
  labels:
    app: web
spec:
  containers:
  - name: web
    image: thtom/webappcolor
    ports:
      - containerPort: 8080
    env:
      - name: APP_COLOR
        value: red