version: '2'
services:
  web:
    image:  php:apache
    depends_on:
      - api
    ports:
      - "8082:80"
    volumes:
      - ./website:/var/www/html
    environment:
      - USERNAME=toto
      - PASSWORD=python
    networks:
      - pozos

  api:
    image: choco1992/api:1
    ports:
      - "8081:5000"
    volumes:
      - ./simple_api/student_age.json:/data/student_age.json
    networks:
      - pozos

networks:
  pozos: