# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "ansible" do |ansible|
    ansible.vm.box = "generic/ubuntu2004"
    ansible.vm.box_version = "1"
    ansible.vm.network "public_network"
    ansible.vm.hostname = "ansible"
    ansible.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = 8192
      v.vmx["numvcpus"] = 2
    end
    ansible.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
    apt-get upgrade -y
    apt-get install zfsutils-linux lxd -y
    echo "L'adresse IP de votre machine $HOSTNAME est : $(hostname -I)"
    SHELL
  end
end