# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "Docker" do |dockerconf|
    dockerconf.vm.box = "centos/7"
    dockerconf.vm.hostname = "Docker-CentOS"
    dockerconf.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = 1024
      v.vmx["numvcpus"] = 2
    end
    dockerconf.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      curl -fsSL https://get.docker.com -o get-docker.sh
      sudo sh get-docker.sh
      sudo usermod -aG docker vagrant
      sudo systemctl enable docker
      sudo systemctl start docker
      SHELL
  end

end
