# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.define "minikube" do |minikube|
    minikube.vm.box = "thtom/Fedora-35-Server-arm64-FR"
    minikube.vm.hostname = "minikube"
    minikube.vm.network "private_network"
    minikube.vm.provider "vmware_desktop" do |v|
      v.vmx["memsize"] = 4096
      v.vmx["numvcpus"] = 2
    end
    minikube.vm.provision "shell", inline: <<-SHELL
      sudo yum update -y
      sudo yum -y install epel-release
      sudo yum -y install libvirt qemu-kvm virt-install virt-top libguestfs-tools bridge-utils wget
      sudo yum install socat -y
      sudo yum install -y conntrack
      curl -fsSL https://get.docker.com -o get-docker.sh
      sudo sh get-docker.sh
      sudo usermod -aG docker vagrant
      sudo systemctl enable docker
      sudo systemctl start docker
      curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/arm64/kubectl
      chmod +x ./kubectl
      sudo mv ./kubectl /usr/local/bin/kubectl
      curl -Lo minikube https://github.com/kubernetes/minikube/releases/download/v1.25.1/minikube-linux-arm64 && chmod +x minikube
      sudo mkdir -p /usr/local/bin/
      sudo install minikube /usr/local/bin/
      sudo swapoff -a
      sudo sed -i '/ swap / s/^\(.*\)$/#\1/g' /etc/fstab
      curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
      sudo chmod 700 get_helm.sh
      sudo bash get_helm.sh
      sudo rm get-docker.sh
      sudo rm get_helm.sh
      sudo systemctl stop firewalld
      sudo systemctl disable firewalld
      sudo grubby --update-kernel ALL --args selinux=0
      sudo reboot
      echo "Pour démarrer Minikube tapez la commande : minikube start --driver=none"
      SHELL
  end

end