# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

    config.vm.box = "thtom/Fedora-35-Server-arm64-FR"
    config.vm.box_version = "1.0.0"
    config.vm.provision "shell", inline: <<-SHELL
       sudo yum update -y
       curl -fsSL https://get.docker.com -o get-docker.sh
       sudo sh get-docker.sh
       sudo usermod -aG docker vagrant
       sudo systemctl enable docker
       sudo systemctl start docker
       echo "L'adresse IP de votre machine $HOSTNAME est : $(hostname -I)"
    SHELL
  end
  